services:
  # Combined Frontend and Backend Service
  - type: web
    name: resume-generator
    env: node
    region: oregon
    plan: free
    buildCommand: |
      npm install
      cd frontend
      npm install react@18.2.0 react-dom@18.2.0 --save
      npm install
      npm run build
      cd ../backend
      npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3030
      - key: HOST
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://resume-generator.onrender.com
    nodeVersion: 18.20.2 